[package]
name = "i2auth"
version = "0.1.0"
authors = ["Vlad Teletin <vladtel.dev@gmail.com>"]
edition = "2021"
repository = "https://github.com/ChromaMaster/i2auth"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
